/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as AuthenticatedRouteRouteImport } from "./routes/_authenticated/route";
import { Route as OrganisationsRouteRouteImport } from "./routes/_organisations/route";
import { Route as AuthenticatedIndexRouteImport } from "./routes/_authenticated/index";
import { Route as AuthenticatedCredentialSchemasRouteRouteImport } from "./routes/_authenticated/credential-schemas/route";
import { Route as AuthenticatedIdentitiesRouteRouteImport } from "./routes/_authenticated/identities/route";
import { Route as AuthenticatedIntegrationsRouteRouteImport } from "./routes/_authenticated/integrations/route";
import { Route as AuthenticatedIssuerRouteRouteImport } from "./routes/_authenticated/issuer/route";
import { Route as AuthenticatedKeysRouteRouteImport } from "./routes/_authenticated/keys/route";
import { Route as AuthenticatedOrganisationRouteRouteImport } from "./routes/_authenticated/organisation/route";
import { Route as AuthenticatedProofSchemasRouteRouteImport } from "./routes/_authenticated/proof-schemas/route";
import { Route as AuthenticatedSettingsRouteRouteImport } from "./routes/_authenticated/settings/route";
import { Route as AuthenticatedStatusListsRouteRouteImport } from "./routes/_authenticated/status-lists/route";
import { Route as AuthenticatedTestingRouteRouteImport } from "./routes/_authenticated/testing/route";
import { Route as OrganisationsExtensionsRouteRouteImport } from "./routes/_organisations/extensions/route";
import { Route as OrganisationsIssuerDefinitionsRouteRouteImport } from "./routes/_organisations/issuer-definitions/route";
import { Route as OrganisationsOrganisationsRouteRouteImport } from "./routes/_organisations/organisations/route";
import { Route as PublicTicketRouteImport } from "./routes/public/ticket";
import { Route as AuthenticatedCredentialSchemasIndexRouteImport } from "./routes/_authenticated/credential-schemas/index";
import { Route as AuthenticatedCredentialSchemasSchemaIdRouteImport } from "./routes/_authenticated/credential-schemas/$schemaId";
import { Route as AuthenticatedIdentitiesIndexRouteImport } from "./routes/_authenticated/identities/index";
import { Route as AuthenticatedIdentitiesIdentityIdRouteImport } from "./routes/_authenticated/identities/$identityId";
import { Route as AuthenticatedIntegrationsIndexRouteImport } from "./routes/_authenticated/integrations/index";
import { Route as AuthenticatedIntegrationsIntegrationIdRouteImport } from "./routes/_authenticated/integrations/$integrationId";
import { Route as AuthenticatedIssuerIndexRouteImport } from "./routes/_authenticated/issuer/index";
import { Route as AuthenticatedKeysIndexRouteImport } from "./routes/_authenticated/keys/index";
import { Route as AuthenticatedOrganisationIndexRouteImport } from "./routes/_authenticated/organisation/index";
import { Route as AuthenticatedProofSchemasIndexRouteImport } from "./routes/_authenticated/proof-schemas/index";
import { Route as AuthenticatedProofSchemasProofSchemaIdRouteImport } from "./routes/_authenticated/proof-schemas/$proofSchemaId";
import { Route as AuthenticatedSettingsIndexRouteImport } from "./routes/_authenticated/settings/index";
import { Route as AuthenticatedStatusListsIndexRouteImport } from "./routes/_authenticated/status-lists/index";
import { Route as AuthenticatedStatusListsStatusListIdRouteImport } from "./routes/_authenticated/status-lists/$statusListId";
import { Route as AuthenticatedTestingIndexRouteImport } from "./routes/_authenticated/testing/index";
import { Route as OrganisationsExtensionsIndexRouteImport } from "./routes/_organisations/extensions/index";
import { Route as OrganisationsIssuerDefinitionsIndexRouteImport } from "./routes/_organisations/issuer-definitions/index";
import { Route as OrganisationsIssuerDefinitionsIdentityIdRouteImport } from "./routes/_organisations/issuer-definitions/$identityId";
import { Route as OrganisationsOrganisationsIndexRouteImport } from "./routes/_organisations/organisations/index";
import { Route as OrganisationsOrganisationsTenantIdRouteImport } from "./routes/_organisations/organisations/$tenantId";
import { Route as AuthenticatedIssuerSchemaIdIssueRouteImport } from "./routes/_authenticated/issuer/$schemaId/issue";
import { Route as AuthenticatedIssuerSchemaIdTransferRouteImport } from "./routes/_authenticated/issuer/$schemaId/transfer";

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: "/_authenticated",
  getParentRoute: () => rootRouteImport,
} as any);
const OrganisationsRouteRoute = OrganisationsRouteRouteImport.update({
  id: "/_organisations",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AuthenticatedRouteRoute,
} as any);
const AuthenticatedCredentialSchemasRouteRoute =
  AuthenticatedCredentialSchemasRouteRouteImport.update({
    id: "/credential-schemas",
    path: "/credential-schemas",
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any);
const AuthenticatedIdentitiesRouteRoute =
  AuthenticatedIdentitiesRouteRouteImport.update({
    id: "/identities",
    path: "/identities",
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any);
const AuthenticatedIntegrationsRouteRoute =
  AuthenticatedIntegrationsRouteRouteImport.update({
    id: "/integrations",
    path: "/integrations",
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any);
const AuthenticatedIssuerRouteRoute =
  AuthenticatedIssuerRouteRouteImport.update({
    id: "/issuer",
    path: "/issuer",
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any);
const AuthenticatedKeysRouteRoute = AuthenticatedKeysRouteRouteImport.update({
  id: "/keys",
  path: "/keys",
  getParentRoute: () => AuthenticatedRouteRoute,
} as any);
const AuthenticatedOrganisationRouteRoute =
  AuthenticatedOrganisationRouteRouteImport.update({
    id: "/organisation",
    path: "/organisation",
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any);
const AuthenticatedProofSchemasRouteRoute =
  AuthenticatedProofSchemasRouteRouteImport.update({
    id: "/proof-schemas",
    path: "/proof-schemas",
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any);
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: "/settings",
    path: "/settings",
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any);
const AuthenticatedStatusListsRouteRoute =
  AuthenticatedStatusListsRouteRouteImport.update({
    id: "/status-lists",
    path: "/status-lists",
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any);
const AuthenticatedTestingRouteRoute =
  AuthenticatedTestingRouteRouteImport.update({
    id: "/testing",
    path: "/testing",
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any);
const OrganisationsExtensionsRouteRoute =
  OrganisationsExtensionsRouteRouteImport.update({
    id: "/extensions",
    path: "/extensions",
    getParentRoute: () => OrganisationsRouteRoute,
  } as any);
const OrganisationsIssuerDefinitionsRouteRoute =
  OrganisationsIssuerDefinitionsRouteRouteImport.update({
    id: "/issuer-definitions",
    path: "/issuer-definitions",
    getParentRoute: () => OrganisationsRouteRoute,
  } as any);
const OrganisationsOrganisationsRouteRoute =
  OrganisationsOrganisationsRouteRouteImport.update({
    id: "/organisations",
    path: "/organisations",
    getParentRoute: () => OrganisationsRouteRoute,
  } as any);
const PublicTicketRoute = PublicTicketRouteImport.update({
  id: "/public/ticket",
  path: "/public/ticket",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthenticatedCredentialSchemasIndexRoute =
  AuthenticatedCredentialSchemasIndexRouteImport.update({
    id: "/",
    path: "/",
    getParentRoute: () => AuthenticatedCredentialSchemasRouteRoute,
  } as any);
const AuthenticatedCredentialSchemasSchemaIdRoute =
  AuthenticatedCredentialSchemasSchemaIdRouteImport.update({
    id: "/$schemaId",
    path: "/$schemaId",
    getParentRoute: () => AuthenticatedCredentialSchemasRouteRoute,
  } as any);
const AuthenticatedIdentitiesIndexRoute =
  AuthenticatedIdentitiesIndexRouteImport.update({
    id: "/",
    path: "/",
    getParentRoute: () => AuthenticatedIdentitiesRouteRoute,
  } as any);
const AuthenticatedIdentitiesIdentityIdRoute =
  AuthenticatedIdentitiesIdentityIdRouteImport.update({
    id: "/$identityId",
    path: "/$identityId",
    getParentRoute: () => AuthenticatedIdentitiesRouteRoute,
  } as any);
const AuthenticatedIntegrationsIndexRoute =
  AuthenticatedIntegrationsIndexRouteImport.update({
    id: "/",
    path: "/",
    getParentRoute: () => AuthenticatedIntegrationsRouteRoute,
  } as any);
const AuthenticatedIntegrationsIntegrationIdRoute =
  AuthenticatedIntegrationsIntegrationIdRouteImport.update({
    id: "/$integrationId",
    path: "/$integrationId",
    getParentRoute: () => AuthenticatedIntegrationsRouteRoute,
  } as any);
const AuthenticatedIssuerIndexRoute =
  AuthenticatedIssuerIndexRouteImport.update({
    id: "/",
    path: "/",
    getParentRoute: () => AuthenticatedIssuerRouteRoute,
  } as any);
const AuthenticatedKeysIndexRoute = AuthenticatedKeysIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AuthenticatedKeysRouteRoute,
} as any);
const AuthenticatedOrganisationIndexRoute =
  AuthenticatedOrganisationIndexRouteImport.update({
    id: "/",
    path: "/",
    getParentRoute: () => AuthenticatedOrganisationRouteRoute,
  } as any);
const AuthenticatedProofSchemasIndexRoute =
  AuthenticatedProofSchemasIndexRouteImport.update({
    id: "/",
    path: "/",
    getParentRoute: () => AuthenticatedProofSchemasRouteRoute,
  } as any);
const AuthenticatedProofSchemasProofSchemaIdRoute =
  AuthenticatedProofSchemasProofSchemaIdRouteImport.update({
    id: "/$proofSchemaId",
    path: "/$proofSchemaId",
    getParentRoute: () => AuthenticatedProofSchemasRouteRoute,
  } as any);
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: "/",
    path: "/",
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any);
const AuthenticatedStatusListsIndexRoute =
  AuthenticatedStatusListsIndexRouteImport.update({
    id: "/",
    path: "/",
    getParentRoute: () => AuthenticatedStatusListsRouteRoute,
  } as any);
const AuthenticatedStatusListsStatusListIdRoute =
  AuthenticatedStatusListsStatusListIdRouteImport.update({
    id: "/$statusListId",
    path: "/$statusListId",
    getParentRoute: () => AuthenticatedStatusListsRouteRoute,
  } as any);
const AuthenticatedTestingIndexRoute =
  AuthenticatedTestingIndexRouteImport.update({
    id: "/",
    path: "/",
    getParentRoute: () => AuthenticatedTestingRouteRoute,
  } as any);
const OrganisationsExtensionsIndexRoute =
  OrganisationsExtensionsIndexRouteImport.update({
    id: "/",
    path: "/",
    getParentRoute: () => OrganisationsExtensionsRouteRoute,
  } as any);
const OrganisationsIssuerDefinitionsIndexRoute =
  OrganisationsIssuerDefinitionsIndexRouteImport.update({
    id: "/",
    path: "/",
    getParentRoute: () => OrganisationsIssuerDefinitionsRouteRoute,
  } as any);
const OrganisationsIssuerDefinitionsIdentityIdRoute =
  OrganisationsIssuerDefinitionsIdentityIdRouteImport.update({
    id: "/$identityId",
    path: "/$identityId",
    getParentRoute: () => OrganisationsIssuerDefinitionsRouteRoute,
  } as any);
const OrganisationsOrganisationsIndexRoute =
  OrganisationsOrganisationsIndexRouteImport.update({
    id: "/",
    path: "/",
    getParentRoute: () => OrganisationsOrganisationsRouteRoute,
  } as any);
const OrganisationsOrganisationsTenantIdRoute =
  OrganisationsOrganisationsTenantIdRouteImport.update({
    id: "/$tenantId",
    path: "/$tenantId",
    getParentRoute: () => OrganisationsOrganisationsRouteRoute,
  } as any);
const AuthenticatedIssuerSchemaIdIssueRoute =
  AuthenticatedIssuerSchemaIdIssueRouteImport.update({
    id: "/$schemaId/issue",
    path: "/$schemaId/issue",
    getParentRoute: () => AuthenticatedIssuerRouteRoute,
  } as any);
const AuthenticatedIssuerSchemaIdTransferRoute =
  AuthenticatedIssuerSchemaIdTransferRouteImport.update({
    id: "/$schemaId/transfer",
    path: "/$schemaId/transfer",
    getParentRoute: () => AuthenticatedIssuerRouteRoute,
  } as any);

export interface FileRoutesByFullPath {
  "/": typeof AuthenticatedIndexRoute;
  "/credential-schemas": typeof AuthenticatedCredentialSchemasRouteRouteWithChildren;
  "/identities": typeof AuthenticatedIdentitiesRouteRouteWithChildren;
  "/integrations": typeof AuthenticatedIntegrationsRouteRouteWithChildren;
  "/issuer": typeof AuthenticatedIssuerRouteRouteWithChildren;
  "/keys": typeof AuthenticatedKeysRouteRouteWithChildren;
  "/organisation": typeof AuthenticatedOrganisationRouteRouteWithChildren;
  "/proof-schemas": typeof AuthenticatedProofSchemasRouteRouteWithChildren;
  "/settings": typeof AuthenticatedSettingsRouteRouteWithChildren;
  "/status-lists": typeof AuthenticatedStatusListsRouteRouteWithChildren;
  "/testing": typeof AuthenticatedTestingRouteRouteWithChildren;
  "/extensions": typeof OrganisationsExtensionsRouteRouteWithChildren;
  "/issuer-definitions": typeof OrganisationsIssuerDefinitionsRouteRouteWithChildren;
  "/organisations": typeof OrganisationsOrganisationsRouteRouteWithChildren;
  "/public/ticket": typeof PublicTicketRoute;
  "/credential-schemas/$schemaId": typeof AuthenticatedCredentialSchemasSchemaIdRoute;
  "/identities/$identityId": typeof AuthenticatedIdentitiesIdentityIdRoute;
  "/integrations/$integrationId": typeof AuthenticatedIntegrationsIntegrationIdRoute;
  "/proof-schemas/$proofSchemaId": typeof AuthenticatedProofSchemasProofSchemaIdRoute;
  "/status-lists/$statusListId": typeof AuthenticatedStatusListsStatusListIdRoute;
  "/issuer-definitions/$identityId": typeof OrganisationsIssuerDefinitionsIdentityIdRoute;
  "/organisations/$tenantId": typeof OrganisationsOrganisationsTenantIdRoute;
  "/credential-schemas/": typeof AuthenticatedCredentialSchemasIndexRoute;
  "/identities/": typeof AuthenticatedIdentitiesIndexRoute;
  "/integrations/": typeof AuthenticatedIntegrationsIndexRoute;
  "/issuer/": typeof AuthenticatedIssuerIndexRoute;
  "/keys/": typeof AuthenticatedKeysIndexRoute;
  "/organisation/": typeof AuthenticatedOrganisationIndexRoute;
  "/proof-schemas/": typeof AuthenticatedProofSchemasIndexRoute;
  "/settings/": typeof AuthenticatedSettingsIndexRoute;
  "/status-lists/": typeof AuthenticatedStatusListsIndexRoute;
  "/testing/": typeof AuthenticatedTestingIndexRoute;
  "/extensions/": typeof OrganisationsExtensionsIndexRoute;
  "/issuer-definitions/": typeof OrganisationsIssuerDefinitionsIndexRoute;
  "/organisations/": typeof OrganisationsOrganisationsIndexRoute;
  "/issuer/$schemaId/issue": typeof AuthenticatedIssuerSchemaIdIssueRoute;
  "/issuer/$schemaId/transfer": typeof AuthenticatedIssuerSchemaIdTransferRoute;
}
export interface FileRoutesByTo {
  "/": typeof AuthenticatedIndexRoute;
  "/public/ticket": typeof PublicTicketRoute;
  "/credential-schemas/$schemaId": typeof AuthenticatedCredentialSchemasSchemaIdRoute;
  "/identities/$identityId": typeof AuthenticatedIdentitiesIdentityIdRoute;
  "/integrations/$integrationId": typeof AuthenticatedIntegrationsIntegrationIdRoute;
  "/proof-schemas/$proofSchemaId": typeof AuthenticatedProofSchemasProofSchemaIdRoute;
  "/status-lists/$statusListId": typeof AuthenticatedStatusListsStatusListIdRoute;
  "/issuer-definitions/$identityId": typeof OrganisationsIssuerDefinitionsIdentityIdRoute;
  "/organisations/$tenantId": typeof OrganisationsOrganisationsTenantIdRoute;
  "/credential-schemas": typeof AuthenticatedCredentialSchemasIndexRoute;
  "/identities": typeof AuthenticatedIdentitiesIndexRoute;
  "/integrations": typeof AuthenticatedIntegrationsIndexRoute;
  "/issuer": typeof AuthenticatedIssuerIndexRoute;
  "/keys": typeof AuthenticatedKeysIndexRoute;
  "/organisation": typeof AuthenticatedOrganisationIndexRoute;
  "/proof-schemas": typeof AuthenticatedProofSchemasIndexRoute;
  "/settings": typeof AuthenticatedSettingsIndexRoute;
  "/status-lists": typeof AuthenticatedStatusListsIndexRoute;
  "/testing": typeof AuthenticatedTestingIndexRoute;
  "/extensions": typeof OrganisationsExtensionsIndexRoute;
  "/issuer-definitions": typeof OrganisationsIssuerDefinitionsIndexRoute;
  "/organisations": typeof OrganisationsOrganisationsIndexRoute;
  "/issuer/$schemaId/issue": typeof AuthenticatedIssuerSchemaIdIssueRoute;
  "/issuer/$schemaId/transfer": typeof AuthenticatedIssuerSchemaIdTransferRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/_authenticated": typeof AuthenticatedRouteRouteWithChildren;
  "/_organisations": typeof OrganisationsRouteRouteWithChildren;
  "/_authenticated/credential-schemas": typeof AuthenticatedCredentialSchemasRouteRouteWithChildren;
  "/_authenticated/identities": typeof AuthenticatedIdentitiesRouteRouteWithChildren;
  "/_authenticated/integrations": typeof AuthenticatedIntegrationsRouteRouteWithChildren;
  "/_authenticated/issuer": typeof AuthenticatedIssuerRouteRouteWithChildren;
  "/_authenticated/keys": typeof AuthenticatedKeysRouteRouteWithChildren;
  "/_authenticated/organisation": typeof AuthenticatedOrganisationRouteRouteWithChildren;
  "/_authenticated/proof-schemas": typeof AuthenticatedProofSchemasRouteRouteWithChildren;
  "/_authenticated/settings": typeof AuthenticatedSettingsRouteRouteWithChildren;
  "/_authenticated/status-lists": typeof AuthenticatedStatusListsRouteRouteWithChildren;
  "/_authenticated/testing": typeof AuthenticatedTestingRouteRouteWithChildren;
  "/_organisations/extensions": typeof OrganisationsExtensionsRouteRouteWithChildren;
  "/_organisations/issuer-definitions": typeof OrganisationsIssuerDefinitionsRouteRouteWithChildren;
  "/_organisations/organisations": typeof OrganisationsOrganisationsRouteRouteWithChildren;
  "/public/ticket": typeof PublicTicketRoute;
  "/_authenticated/": typeof AuthenticatedIndexRoute;
  "/_authenticated/credential-schemas/$schemaId": typeof AuthenticatedCredentialSchemasSchemaIdRoute;
  "/_authenticated/identities/$identityId": typeof AuthenticatedIdentitiesIdentityIdRoute;
  "/_authenticated/integrations/$integrationId": typeof AuthenticatedIntegrationsIntegrationIdRoute;
  "/_authenticated/proof-schemas/$proofSchemaId": typeof AuthenticatedProofSchemasProofSchemaIdRoute;
  "/_authenticated/status-lists/$statusListId": typeof AuthenticatedStatusListsStatusListIdRoute;
  "/_organisations/issuer-definitions/$identityId": typeof OrganisationsIssuerDefinitionsIdentityIdRoute;
  "/_organisations/organisations/$tenantId": typeof OrganisationsOrganisationsTenantIdRoute;
  "/_authenticated/credential-schemas/": typeof AuthenticatedCredentialSchemasIndexRoute;
  "/_authenticated/identities/": typeof AuthenticatedIdentitiesIndexRoute;
  "/_authenticated/integrations/": typeof AuthenticatedIntegrationsIndexRoute;
  "/_authenticated/issuer/": typeof AuthenticatedIssuerIndexRoute;
  "/_authenticated/keys/": typeof AuthenticatedKeysIndexRoute;
  "/_authenticated/organisation/": typeof AuthenticatedOrganisationIndexRoute;
  "/_authenticated/proof-schemas/": typeof AuthenticatedProofSchemasIndexRoute;
  "/_authenticated/settings/": typeof AuthenticatedSettingsIndexRoute;
  "/_authenticated/status-lists/": typeof AuthenticatedStatusListsIndexRoute;
  "/_authenticated/testing/": typeof AuthenticatedTestingIndexRoute;
  "/_organisations/extensions/": typeof OrganisationsExtensionsIndexRoute;
  "/_organisations/issuer-definitions/": typeof OrganisationsIssuerDefinitionsIndexRoute;
  "/_organisations/organisations/": typeof OrganisationsOrganisationsIndexRoute;
  "/_authenticated/issuer/$schemaId/issue": typeof AuthenticatedIssuerSchemaIdIssueRoute;
  "/_authenticated/issuer/$schemaId/transfer": typeof AuthenticatedIssuerSchemaIdTransferRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/credential-schemas"
    | "/identities"
    | "/integrations"
    | "/issuer"
    | "/keys"
    | "/organisation"
    | "/proof-schemas"
    | "/settings"
    | "/status-lists"
    | "/testing"
    | "/extensions"
    | "/issuer-definitions"
    | "/organisations"
    | "/public/ticket"
    | "/credential-schemas/$schemaId"
    | "/identities/$identityId"
    | "/integrations/$integrationId"
    | "/proof-schemas/$proofSchemaId"
    | "/status-lists/$statusListId"
    | "/issuer-definitions/$identityId"
    | "/organisations/$tenantId"
    | "/credential-schemas/"
    | "/identities/"
    | "/integrations/"
    | "/issuer/"
    | "/keys/"
    | "/organisation/"
    | "/proof-schemas/"
    | "/settings/"
    | "/status-lists/"
    | "/testing/"
    | "/extensions/"
    | "/issuer-definitions/"
    | "/organisations/"
    | "/issuer/$schemaId/issue"
    | "/issuer/$schemaId/transfer";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/public/ticket"
    | "/credential-schemas/$schemaId"
    | "/identities/$identityId"
    | "/integrations/$integrationId"
    | "/proof-schemas/$proofSchemaId"
    | "/status-lists/$statusListId"
    | "/issuer-definitions/$identityId"
    | "/organisations/$tenantId"
    | "/credential-schemas"
    | "/identities"
    | "/integrations"
    | "/issuer"
    | "/keys"
    | "/organisation"
    | "/proof-schemas"
    | "/settings"
    | "/status-lists"
    | "/testing"
    | "/extensions"
    | "/issuer-definitions"
    | "/organisations"
    | "/issuer/$schemaId/issue"
    | "/issuer/$schemaId/transfer";
  id:
    | "__root__"
    | "/_authenticated"
    | "/_organisations"
    | "/_authenticated/credential-schemas"
    | "/_authenticated/identities"
    | "/_authenticated/integrations"
    | "/_authenticated/issuer"
    | "/_authenticated/keys"
    | "/_authenticated/organisation"
    | "/_authenticated/proof-schemas"
    | "/_authenticated/settings"
    | "/_authenticated/status-lists"
    | "/_authenticated/testing"
    | "/_organisations/extensions"
    | "/_organisations/issuer-definitions"
    | "/_organisations/organisations"
    | "/public/ticket"
    | "/_authenticated/"
    | "/_authenticated/credential-schemas/$schemaId"
    | "/_authenticated/identities/$identityId"
    | "/_authenticated/integrations/$integrationId"
    | "/_authenticated/proof-schemas/$proofSchemaId"
    | "/_authenticated/status-lists/$statusListId"
    | "/_organisations/issuer-definitions/$identityId"
    | "/_organisations/organisations/$tenantId"
    | "/_authenticated/credential-schemas/"
    | "/_authenticated/identities/"
    | "/_authenticated/integrations/"
    | "/_authenticated/issuer/"
    | "/_authenticated/keys/"
    | "/_authenticated/organisation/"
    | "/_authenticated/proof-schemas/"
    | "/_authenticated/settings/"
    | "/_authenticated/status-lists/"
    | "/_authenticated/testing/"
    | "/_organisations/extensions/"
    | "/_organisations/issuer-definitions/"
    | "/_organisations/organisations/"
    | "/_authenticated/issuer/$schemaId/issue"
    | "/_authenticated/issuer/$schemaId/transfer";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren;
  OrganisationsRouteRoute: typeof OrganisationsRouteRouteWithChildren;
  PublicTicketRoute: typeof PublicTicketRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/_authenticated": {
      id: "/_authenticated";
      path: "";
      fullPath: "/";
      preLoaderRoute: typeof AuthenticatedRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_organisations": {
      id: "/_organisations";
      path: "";
      fullPath: "/";
      preLoaderRoute: typeof OrganisationsRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_authenticated/": {
      id: "/_authenticated/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof AuthenticatedIndexRouteImport;
      parentRoute: typeof AuthenticatedRouteRoute;
    };
    "/_authenticated/credential-schemas": {
      id: "/_authenticated/credential-schemas";
      path: "/credential-schemas";
      fullPath: "/credential-schemas";
      preLoaderRoute: typeof AuthenticatedCredentialSchemasRouteRouteImport;
      parentRoute: typeof AuthenticatedRouteRoute;
    };
    "/_authenticated/identities": {
      id: "/_authenticated/identities";
      path: "/identities";
      fullPath: "/identities";
      preLoaderRoute: typeof AuthenticatedIdentitiesRouteRouteImport;
      parentRoute: typeof AuthenticatedRouteRoute;
    };
    "/_authenticated/integrations": {
      id: "/_authenticated/integrations";
      path: "/integrations";
      fullPath: "/integrations";
      preLoaderRoute: typeof AuthenticatedIntegrationsRouteRouteImport;
      parentRoute: typeof AuthenticatedRouteRoute;
    };
    "/_authenticated/issuer": {
      id: "/_authenticated/issuer";
      path: "/issuer";
      fullPath: "/issuer";
      preLoaderRoute: typeof AuthenticatedIssuerRouteRouteImport;
      parentRoute: typeof AuthenticatedRouteRoute;
    };
    "/_authenticated/keys": {
      id: "/_authenticated/keys";
      path: "/keys";
      fullPath: "/keys";
      preLoaderRoute: typeof AuthenticatedKeysRouteRouteImport;
      parentRoute: typeof AuthenticatedRouteRoute;
    };
    "/_authenticated/organisation": {
      id: "/_authenticated/organisation";
      path: "/organisation";
      fullPath: "/organisation";
      preLoaderRoute: typeof AuthenticatedOrganisationRouteRouteImport;
      parentRoute: typeof AuthenticatedRouteRoute;
    };
    "/_authenticated/proof-schemas": {
      id: "/_authenticated/proof-schemas";
      path: "/proof-schemas";
      fullPath: "/proof-schemas";
      preLoaderRoute: typeof AuthenticatedProofSchemasRouteRouteImport;
      parentRoute: typeof AuthenticatedRouteRoute;
    };
    "/_authenticated/settings": {
      id: "/_authenticated/settings";
      path: "/settings";
      fullPath: "/settings";
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport;
      parentRoute: typeof AuthenticatedRouteRoute;
    };
    "/_authenticated/status-lists": {
      id: "/_authenticated/status-lists";
      path: "/status-lists";
      fullPath: "/status-lists";
      preLoaderRoute: typeof AuthenticatedStatusListsRouteRouteImport;
      parentRoute: typeof AuthenticatedRouteRoute;
    };
    "/_authenticated/testing": {
      id: "/_authenticated/testing";
      path: "/testing";
      fullPath: "/testing";
      preLoaderRoute: typeof AuthenticatedTestingRouteRouteImport;
      parentRoute: typeof AuthenticatedRouteRoute;
    };
    "/_organisations/extensions": {
      id: "/_organisations/extensions";
      path: "/extensions";
      fullPath: "/extensions";
      preLoaderRoute: typeof OrganisationsExtensionsRouteRouteImport;
      parentRoute: typeof OrganisationsRouteRoute;
    };
    "/_organisations/issuer-definitions": {
      id: "/_organisations/issuer-definitions";
      path: "/issuer-definitions";
      fullPath: "/issuer-definitions";
      preLoaderRoute: typeof OrganisationsIssuerDefinitionsRouteRouteImport;
      parentRoute: typeof OrganisationsRouteRoute;
    };
    "/_organisations/organisations": {
      id: "/_organisations/organisations";
      path: "/organisations";
      fullPath: "/organisations";
      preLoaderRoute: typeof OrganisationsOrganisationsRouteRouteImport;
      parentRoute: typeof OrganisationsRouteRoute;
    };
    "/public/ticket": {
      id: "/public/ticket";
      path: "/public/ticket";
      fullPath: "/public/ticket";
      preLoaderRoute: typeof PublicTicketRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_authenticated/credential-schemas/": {
      id: "/_authenticated/credential-schemas/";
      path: "/";
      fullPath: "/credential-schemas/";
      preLoaderRoute: typeof AuthenticatedCredentialSchemasIndexRouteImport;
      parentRoute: typeof AuthenticatedCredentialSchemasRouteRoute;
    };
    "/_authenticated/credential-schemas/$schemaId": {
      id: "/_authenticated/credential-schemas/$schemaId";
      path: "/$schemaId";
      fullPath: "/credential-schemas/$schemaId";
      preLoaderRoute: typeof AuthenticatedCredentialSchemasSchemaIdRouteImport;
      parentRoute: typeof AuthenticatedCredentialSchemasRouteRoute;
    };
    "/_authenticated/identities/": {
      id: "/_authenticated/identities/";
      path: "/";
      fullPath: "/identities/";
      preLoaderRoute: typeof AuthenticatedIdentitiesIndexRouteImport;
      parentRoute: typeof AuthenticatedIdentitiesRouteRoute;
    };
    "/_authenticated/identities/$identityId": {
      id: "/_authenticated/identities/$identityId";
      path: "/$identityId";
      fullPath: "/identities/$identityId";
      preLoaderRoute: typeof AuthenticatedIdentitiesIdentityIdRouteImport;
      parentRoute: typeof AuthenticatedIdentitiesRouteRoute;
    };
    "/_authenticated/integrations/": {
      id: "/_authenticated/integrations/";
      path: "/";
      fullPath: "/integrations/";
      preLoaderRoute: typeof AuthenticatedIntegrationsIndexRouteImport;
      parentRoute: typeof AuthenticatedIntegrationsRouteRoute;
    };
    "/_authenticated/integrations/$integrationId": {
      id: "/_authenticated/integrations/$integrationId";
      path: "/$integrationId";
      fullPath: "/integrations/$integrationId";
      preLoaderRoute: typeof AuthenticatedIntegrationsIntegrationIdRouteImport;
      parentRoute: typeof AuthenticatedIntegrationsRouteRoute;
    };
    "/_authenticated/issuer/": {
      id: "/_authenticated/issuer/";
      path: "/";
      fullPath: "/issuer/";
      preLoaderRoute: typeof AuthenticatedIssuerIndexRouteImport;
      parentRoute: typeof AuthenticatedIssuerRouteRoute;
    };
    "/_authenticated/keys/": {
      id: "/_authenticated/keys/";
      path: "/";
      fullPath: "/keys/";
      preLoaderRoute: typeof AuthenticatedKeysIndexRouteImport;
      parentRoute: typeof AuthenticatedKeysRouteRoute;
    };
    "/_authenticated/organisation/": {
      id: "/_authenticated/organisation/";
      path: "/";
      fullPath: "/organisation/";
      preLoaderRoute: typeof AuthenticatedOrganisationIndexRouteImport;
      parentRoute: typeof AuthenticatedOrganisationRouteRoute;
    };
    "/_authenticated/proof-schemas/": {
      id: "/_authenticated/proof-schemas/";
      path: "/";
      fullPath: "/proof-schemas/";
      preLoaderRoute: typeof AuthenticatedProofSchemasIndexRouteImport;
      parentRoute: typeof AuthenticatedProofSchemasRouteRoute;
    };
    "/_authenticated/proof-schemas/$proofSchemaId": {
      id: "/_authenticated/proof-schemas/$proofSchemaId";
      path: "/$proofSchemaId";
      fullPath: "/proof-schemas/$proofSchemaId";
      preLoaderRoute: typeof AuthenticatedProofSchemasProofSchemaIdRouteImport;
      parentRoute: typeof AuthenticatedProofSchemasRouteRoute;
    };
    "/_authenticated/settings/": {
      id: "/_authenticated/settings/";
      path: "/";
      fullPath: "/settings/";
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport;
      parentRoute: typeof AuthenticatedSettingsRouteRoute;
    };
    "/_authenticated/status-lists/": {
      id: "/_authenticated/status-lists/";
      path: "/";
      fullPath: "/status-lists/";
      preLoaderRoute: typeof AuthenticatedStatusListsIndexRouteImport;
      parentRoute: typeof AuthenticatedStatusListsRouteRoute;
    };
    "/_authenticated/status-lists/$statusListId": {
      id: "/_authenticated/status-lists/$statusListId";
      path: "/$statusListId";
      fullPath: "/status-lists/$statusListId";
      preLoaderRoute: typeof AuthenticatedStatusListsStatusListIdRouteImport;
      parentRoute: typeof AuthenticatedStatusListsRouteRoute;
    };
    "/_authenticated/testing/": {
      id: "/_authenticated/testing/";
      path: "/";
      fullPath: "/testing/";
      preLoaderRoute: typeof AuthenticatedTestingIndexRouteImport;
      parentRoute: typeof AuthenticatedTestingRouteRoute;
    };
    "/_organisations/extensions/": {
      id: "/_organisations/extensions/";
      path: "/";
      fullPath: "/extensions/";
      preLoaderRoute: typeof OrganisationsExtensionsIndexRouteImport;
      parentRoute: typeof OrganisationsExtensionsRouteRoute;
    };
    "/_organisations/issuer-definitions/": {
      id: "/_organisations/issuer-definitions/";
      path: "/";
      fullPath: "/issuer-definitions/";
      preLoaderRoute: typeof OrganisationsIssuerDefinitionsIndexRouteImport;
      parentRoute: typeof OrganisationsIssuerDefinitionsRouteRoute;
    };
    "/_organisations/issuer-definitions/$identityId": {
      id: "/_organisations/issuer-definitions/$identityId";
      path: "/$identityId";
      fullPath: "/issuer-definitions/$identityId";
      preLoaderRoute: typeof OrganisationsIssuerDefinitionsIdentityIdRouteImport;
      parentRoute: typeof OrganisationsIssuerDefinitionsRouteRoute;
    };
    "/_organisations/organisations/": {
      id: "/_organisations/organisations/";
      path: "/";
      fullPath: "/organisations/";
      preLoaderRoute: typeof OrganisationsOrganisationsIndexRouteImport;
      parentRoute: typeof OrganisationsOrganisationsRouteRoute;
    };
    "/_organisations/organisations/$tenantId": {
      id: "/_organisations/organisations/$tenantId";
      path: "/$tenantId";
      fullPath: "/organisations/$tenantId";
      preLoaderRoute: typeof OrganisationsOrganisationsTenantIdRouteImport;
      parentRoute: typeof OrganisationsOrganisationsRouteRoute;
    };
    "/_authenticated/issuer/$schemaId/issue": {
      id: "/_authenticated/issuer/$schemaId/issue";
      path: "/$schemaId/issue";
      fullPath: "/issuer/$schemaId/issue";
      preLoaderRoute: typeof AuthenticatedIssuerSchemaIdIssueRouteImport;
      parentRoute: typeof AuthenticatedIssuerRouteRoute;
    };
    "/_authenticated/issuer/$schemaId/transfer": {
      id: "/_authenticated/issuer/$schemaId/transfer";
      path: "/$schemaId/transfer";
      fullPath: "/issuer/$schemaId/transfer";
      preLoaderRoute: typeof AuthenticatedIssuerSchemaIdTransferRouteImport;
      parentRoute: typeof AuthenticatedIssuerRouteRoute;
    };
  }
}

interface AuthenticatedCredentialSchemasRouteRouteChildren {
  AuthenticatedCredentialSchemasSchemaIdRoute: typeof AuthenticatedCredentialSchemasSchemaIdRoute;
  AuthenticatedCredentialSchemasIndexRoute: typeof AuthenticatedCredentialSchemasIndexRoute;
}

const AuthenticatedCredentialSchemasRouteRouteChildren: AuthenticatedCredentialSchemasRouteRouteChildren =
  {
    AuthenticatedCredentialSchemasSchemaIdRoute:
      AuthenticatedCredentialSchemasSchemaIdRoute,
    AuthenticatedCredentialSchemasIndexRoute:
      AuthenticatedCredentialSchemasIndexRoute,
  };

const AuthenticatedCredentialSchemasRouteRouteWithChildren =
  AuthenticatedCredentialSchemasRouteRoute._addFileChildren(
    AuthenticatedCredentialSchemasRouteRouteChildren,
  );

interface AuthenticatedIdentitiesRouteRouteChildren {
  AuthenticatedIdentitiesIdentityIdRoute: typeof AuthenticatedIdentitiesIdentityIdRoute;
  AuthenticatedIdentitiesIndexRoute: typeof AuthenticatedIdentitiesIndexRoute;
}

const AuthenticatedIdentitiesRouteRouteChildren: AuthenticatedIdentitiesRouteRouteChildren =
  {
    AuthenticatedIdentitiesIdentityIdRoute:
      AuthenticatedIdentitiesIdentityIdRoute,
    AuthenticatedIdentitiesIndexRoute: AuthenticatedIdentitiesIndexRoute,
  };

const AuthenticatedIdentitiesRouteRouteWithChildren =
  AuthenticatedIdentitiesRouteRoute._addFileChildren(
    AuthenticatedIdentitiesRouteRouteChildren,
  );

interface AuthenticatedIntegrationsRouteRouteChildren {
  AuthenticatedIntegrationsIntegrationIdRoute: typeof AuthenticatedIntegrationsIntegrationIdRoute;
  AuthenticatedIntegrationsIndexRoute: typeof AuthenticatedIntegrationsIndexRoute;
}

const AuthenticatedIntegrationsRouteRouteChildren: AuthenticatedIntegrationsRouteRouteChildren =
  {
    AuthenticatedIntegrationsIntegrationIdRoute:
      AuthenticatedIntegrationsIntegrationIdRoute,
    AuthenticatedIntegrationsIndexRoute: AuthenticatedIntegrationsIndexRoute,
  };

const AuthenticatedIntegrationsRouteRouteWithChildren =
  AuthenticatedIntegrationsRouteRoute._addFileChildren(
    AuthenticatedIntegrationsRouteRouteChildren,
  );

interface AuthenticatedIssuerRouteRouteChildren {
  AuthenticatedIssuerIndexRoute: typeof AuthenticatedIssuerIndexRoute;
  AuthenticatedIssuerSchemaIdIssueRoute: typeof AuthenticatedIssuerSchemaIdIssueRoute;
  AuthenticatedIssuerSchemaIdTransferRoute: typeof AuthenticatedIssuerSchemaIdTransferRoute;
}

const AuthenticatedIssuerRouteRouteChildren: AuthenticatedIssuerRouteRouteChildren =
  {
    AuthenticatedIssuerIndexRoute: AuthenticatedIssuerIndexRoute,
    AuthenticatedIssuerSchemaIdIssueRoute:
      AuthenticatedIssuerSchemaIdIssueRoute,
    AuthenticatedIssuerSchemaIdTransferRoute:
      AuthenticatedIssuerSchemaIdTransferRoute,
  };

const AuthenticatedIssuerRouteRouteWithChildren =
  AuthenticatedIssuerRouteRoute._addFileChildren(
    AuthenticatedIssuerRouteRouteChildren,
  );

interface AuthenticatedKeysRouteRouteChildren {
  AuthenticatedKeysIndexRoute: typeof AuthenticatedKeysIndexRoute;
}

const AuthenticatedKeysRouteRouteChildren: AuthenticatedKeysRouteRouteChildren =
  {
    AuthenticatedKeysIndexRoute: AuthenticatedKeysIndexRoute,
  };

const AuthenticatedKeysRouteRouteWithChildren =
  AuthenticatedKeysRouteRoute._addFileChildren(
    AuthenticatedKeysRouteRouteChildren,
  );

interface AuthenticatedOrganisationRouteRouteChildren {
  AuthenticatedOrganisationIndexRoute: typeof AuthenticatedOrganisationIndexRoute;
}

const AuthenticatedOrganisationRouteRouteChildren: AuthenticatedOrganisationRouteRouteChildren =
  {
    AuthenticatedOrganisationIndexRoute: AuthenticatedOrganisationIndexRoute,
  };

const AuthenticatedOrganisationRouteRouteWithChildren =
  AuthenticatedOrganisationRouteRoute._addFileChildren(
    AuthenticatedOrganisationRouteRouteChildren,
  );

interface AuthenticatedProofSchemasRouteRouteChildren {
  AuthenticatedProofSchemasProofSchemaIdRoute: typeof AuthenticatedProofSchemasProofSchemaIdRoute;
  AuthenticatedProofSchemasIndexRoute: typeof AuthenticatedProofSchemasIndexRoute;
}

const AuthenticatedProofSchemasRouteRouteChildren: AuthenticatedProofSchemasRouteRouteChildren =
  {
    AuthenticatedProofSchemasProofSchemaIdRoute:
      AuthenticatedProofSchemasProofSchemaIdRoute,
    AuthenticatedProofSchemasIndexRoute: AuthenticatedProofSchemasIndexRoute,
  };

const AuthenticatedProofSchemasRouteRouteWithChildren =
  AuthenticatedProofSchemasRouteRoute._addFileChildren(
    AuthenticatedProofSchemasRouteRouteChildren,
  );

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute;
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  };

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  );

interface AuthenticatedStatusListsRouteRouteChildren {
  AuthenticatedStatusListsStatusListIdRoute: typeof AuthenticatedStatusListsStatusListIdRoute;
  AuthenticatedStatusListsIndexRoute: typeof AuthenticatedStatusListsIndexRoute;
}

const AuthenticatedStatusListsRouteRouteChildren: AuthenticatedStatusListsRouteRouteChildren =
  {
    AuthenticatedStatusListsStatusListIdRoute:
      AuthenticatedStatusListsStatusListIdRoute,
    AuthenticatedStatusListsIndexRoute: AuthenticatedStatusListsIndexRoute,
  };

const AuthenticatedStatusListsRouteRouteWithChildren =
  AuthenticatedStatusListsRouteRoute._addFileChildren(
    AuthenticatedStatusListsRouteRouteChildren,
  );

interface AuthenticatedTestingRouteRouteChildren {
  AuthenticatedTestingIndexRoute: typeof AuthenticatedTestingIndexRoute;
}

const AuthenticatedTestingRouteRouteChildren: AuthenticatedTestingRouteRouteChildren =
  {
    AuthenticatedTestingIndexRoute: AuthenticatedTestingIndexRoute,
  };

const AuthenticatedTestingRouteRouteWithChildren =
  AuthenticatedTestingRouteRoute._addFileChildren(
    AuthenticatedTestingRouteRouteChildren,
  );

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCredentialSchemasRouteRoute: typeof AuthenticatedCredentialSchemasRouteRouteWithChildren;
  AuthenticatedIdentitiesRouteRoute: typeof AuthenticatedIdentitiesRouteRouteWithChildren;
  AuthenticatedIntegrationsRouteRoute: typeof AuthenticatedIntegrationsRouteRouteWithChildren;
  AuthenticatedIssuerRouteRoute: typeof AuthenticatedIssuerRouteRouteWithChildren;
  AuthenticatedKeysRouteRoute: typeof AuthenticatedKeysRouteRouteWithChildren;
  AuthenticatedOrganisationRouteRoute: typeof AuthenticatedOrganisationRouteRouteWithChildren;
  AuthenticatedProofSchemasRouteRoute: typeof AuthenticatedProofSchemasRouteRouteWithChildren;
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren;
  AuthenticatedStatusListsRouteRoute: typeof AuthenticatedStatusListsRouteRouteWithChildren;
  AuthenticatedTestingRouteRoute: typeof AuthenticatedTestingRouteRouteWithChildren;
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute;
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCredentialSchemasRouteRoute:
    AuthenticatedCredentialSchemasRouteRouteWithChildren,
  AuthenticatedIdentitiesRouteRoute:
    AuthenticatedIdentitiesRouteRouteWithChildren,
  AuthenticatedIntegrationsRouteRoute:
    AuthenticatedIntegrationsRouteRouteWithChildren,
  AuthenticatedIssuerRouteRoute: AuthenticatedIssuerRouteRouteWithChildren,
  AuthenticatedKeysRouteRoute: AuthenticatedKeysRouteRouteWithChildren,
  AuthenticatedOrganisationRouteRoute:
    AuthenticatedOrganisationRouteRouteWithChildren,
  AuthenticatedProofSchemasRouteRoute:
    AuthenticatedProofSchemasRouteRouteWithChildren,
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedStatusListsRouteRoute:
    AuthenticatedStatusListsRouteRouteWithChildren,
  AuthenticatedTestingRouteRoute: AuthenticatedTestingRouteRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
};

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren);

interface OrganisationsExtensionsRouteRouteChildren {
  OrganisationsExtensionsIndexRoute: typeof OrganisationsExtensionsIndexRoute;
}

const OrganisationsExtensionsRouteRouteChildren: OrganisationsExtensionsRouteRouteChildren =
  {
    OrganisationsExtensionsIndexRoute: OrganisationsExtensionsIndexRoute,
  };

const OrganisationsExtensionsRouteRouteWithChildren =
  OrganisationsExtensionsRouteRoute._addFileChildren(
    OrganisationsExtensionsRouteRouteChildren,
  );

interface OrganisationsIssuerDefinitionsRouteRouteChildren {
  OrganisationsIssuerDefinitionsIdentityIdRoute: typeof OrganisationsIssuerDefinitionsIdentityIdRoute;
  OrganisationsIssuerDefinitionsIndexRoute: typeof OrganisationsIssuerDefinitionsIndexRoute;
}

const OrganisationsIssuerDefinitionsRouteRouteChildren: OrganisationsIssuerDefinitionsRouteRouteChildren =
  {
    OrganisationsIssuerDefinitionsIdentityIdRoute:
      OrganisationsIssuerDefinitionsIdentityIdRoute,
    OrganisationsIssuerDefinitionsIndexRoute:
      OrganisationsIssuerDefinitionsIndexRoute,
  };

const OrganisationsIssuerDefinitionsRouteRouteWithChildren =
  OrganisationsIssuerDefinitionsRouteRoute._addFileChildren(
    OrganisationsIssuerDefinitionsRouteRouteChildren,
  );

interface OrganisationsOrganisationsRouteRouteChildren {
  OrganisationsOrganisationsTenantIdRoute: typeof OrganisationsOrganisationsTenantIdRoute;
  OrganisationsOrganisationsIndexRoute: typeof OrganisationsOrganisationsIndexRoute;
}

const OrganisationsOrganisationsRouteRouteChildren: OrganisationsOrganisationsRouteRouteChildren =
  {
    OrganisationsOrganisationsTenantIdRoute:
      OrganisationsOrganisationsTenantIdRoute,
    OrganisationsOrganisationsIndexRoute: OrganisationsOrganisationsIndexRoute,
  };

const OrganisationsOrganisationsRouteRouteWithChildren =
  OrganisationsOrganisationsRouteRoute._addFileChildren(
    OrganisationsOrganisationsRouteRouteChildren,
  );

interface OrganisationsRouteRouteChildren {
  OrganisationsExtensionsRouteRoute: typeof OrganisationsExtensionsRouteRouteWithChildren;
  OrganisationsIssuerDefinitionsRouteRoute: typeof OrganisationsIssuerDefinitionsRouteRouteWithChildren;
  OrganisationsOrganisationsRouteRoute: typeof OrganisationsOrganisationsRouteRouteWithChildren;
}

const OrganisationsRouteRouteChildren: OrganisationsRouteRouteChildren = {
  OrganisationsExtensionsRouteRoute:
    OrganisationsExtensionsRouteRouteWithChildren,
  OrganisationsIssuerDefinitionsRouteRoute:
    OrganisationsIssuerDefinitionsRouteRouteWithChildren,
  OrganisationsOrganisationsRouteRoute:
    OrganisationsOrganisationsRouteRouteWithChildren,
};

const OrganisationsRouteRouteWithChildren =
  OrganisationsRouteRoute._addFileChildren(OrganisationsRouteRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  OrganisationsRouteRoute: OrganisationsRouteRouteWithChildren,
  PublicTicketRoute: PublicTicketRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
