<?xml version="1.0" encoding="UTF-8"?>
<!--
  SPDX-FileCopyrightText: 2026 Ubique Innovation AG and Heidi contributors
  SPDX-License-Identifier: Apache-2.0
-->

<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.heidiverse.heidi.signing</groupId>
        <artifactId>heidi-signing-service</artifactId>
        <version>1.0.0-SNAPSHOT</version>
        <relativePath>../..</relativePath>
    </parent>

    <artifactId>software-provider</artifactId>
    <name>Software Signing Provider</name>

    <dependencies>
        <dependency>
            <groupId>org.heidiverse.heidi.shared</groupId>
            <artifactId>heidi-shared-core</artifactId>
        </dependency>
        <dependency>
            <groupId>org.heidiverse.heidi.shared</groupId>
            <artifactId>heidi-signing-api</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.heidiverse</groupId>
            <artifactId>heidi-software-signerinterface-jvm</artifactId>
            <version>${heidi.signerinterface.version}</version>
        </dependency>
        <dependency>
            <groupId>net.java.dev.jna</groupId>
            <artifactId>jna</artifactId>
            <version>5.13.0</version>
        </dependency>
        <dependency>
            <groupId>com.nimbusds</groupId>
            <artifactId>nimbus-jose-jwt</artifactId>
            <version>10.4.2</version>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-jdbc</artifactId>
        </dependency>
        <dependency>
            <groupId>com.google.crypto.tink</groupId>
            <artifactId>tink</artifactId>
            <version>1.19.0</version>
        </dependency>
        <dependency>
            <groupId>org.heidiverse.heidi.shared</groupId>
            <artifactId>heidi-shared-core</artifactId>
            <version>${project.version}</version>
            <type>test-jar</type>
            <classifier>tests</classifier>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.bouncycastle</groupId>
            <artifactId>bcprov-jdk18on</artifactId>
            <version>1.80</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.bouncycastle</groupId>
            <artifactId>bcpkix-jdk18on</artifactId>
            <version>1.80</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.xerial</groupId>
            <artifactId>sqlite-jdbc</artifactId>
            <version>3.49.1.0</version>
            <scope>test</scope>
        </dependency>
    </dependencies>
</project>
