# SPDX-FileCopyrightText: 2026 Ubique Innovation AG and Heidi contributors
# SPDX-License-Identifier: Apache-2.0

kotlin.code.style=official

# Module specific POM metadata
ARTIFACT_ID=heidi-software-signerinterface
POM_NAME=Heidi Signing Crypto
POM_DESCRIPTION=Native signing cryptography and JVM bindings
ARTIFACT_VERSION=0.2.4
EXPRESSION_ARTIFACT_VERSION=0.1.0

GROUP=org.heidiverse
POM_INCEPTION_YEAR=2025


POM_LICENCE_NAME=Apache-2.0
POM_LICENCE_URL=https://github.com/heidiverse/heidi-platform/blob/main/LICENSE
POM_LICENCE_DIST=repo

POM_DEVELOPER_ID=UbiqueInnovation
POM_DEVELOPER_NAME=Ubique Innovation
POM_DEVELOPER_URL=https://www.ubique.ch/

SONATYPE_STAGING_PROFILE=org.heidiverse


kotlin.mpp.enableCInteropCommonization=true
